### ISSUE TITLE
Upgrade to SODAR Core v0.10

### ISSUE THREAD

**Issue by mikkonie** [bihealth/digestiflow-server#76]
I'm looking into upgrading Digestiflow into the latest SODAR Core version, which gets rid of a lot of issues present in the currently used ancient version and allows for easy upgrading to the latest fixes in the future. Should be trivial, except for the v0.10.0 upgrade which will require some manual work.

Also, deployment must be updated to point to the proper Python version (3.7 and below no longer supported) as well as include the `geticons` command for iconify.

## Tasks

- [x] Upgrade SODAR Core and other dependencies
- [x] Upgrade project to Python 3.8+
- [x] Do upgrades for breaking Django changes since v1.11
- [x] Update icons
- [x] Do other SODAR Core related updates
- [x] Update Docker image building
- [x] Fix search
- [x] Update site settings
- [x] Update utility scripts
- [x] Upgrade Versioneer
- [x] ~~Update CI~~ Oh we are not even running CI, never mind then
- [ ] Update docs
- [x] Ensure tests run
- [x] Enable siteinfo app
- [ ] Fix weird debugtoolbar `TEMPLATES` warning
